name: feat-env
channels:
    - conda-forge
dependencies:
    - python=3.8.5
    - cmake=3.18.2
    - eigen=3.3.7
    - cython=0.29.21
    - pandas=1.1.2
    - scikit-learn=0.23.2
    - setuptools=45.3.0
    - shogun-cpp=6.1.4
    - wheel=0.35.1
    - pip=20.2.3
    - matplotlib
    - jupyter
    - seaborn
    - shap
    - pip:
        - eigency==1.77
        - statannot
        - python-docx
